spring:
  application:
    name: user-service
  profiles:
    default: local
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  port: ${SERVER_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}

info:
  app:
    name: user-service
    version: 0.0.1-SNAPSHOT

security:
  jwt:
    issuer: orderflow-user-service
    access-token-ttl-seconds: 3600
    private-key-location: file:./keys/private.pem
    public-key-location: file:./keys/public.pem

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    path: /swagger-ui.html
    url: /openapi/user-service.yaml
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
    persist-authorization: true