server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://${ORDER_DB_HOST:localhost}:${ORDER_DB_PORT:5432}/${ORDER_DB_NAME:orderflow_order}
    username: ${POSTGRES_USER:orderflow}
    password: ${POSTGRES_PASSWORD:orderflow}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:orderflow}
    password: ${RABBITMQ_PASSWORD:orderflow}
