spring:
  application:
    name: order-service
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8083}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics

  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

  metrics:
    tags:
      application: ${spring.application.name}
info:
  app:
    name: order-service
    version: 0.0.1-SNAPSHOT
