spring:
  application:
    name: inventory-service

  profiles:
    default: local

  datasource:
    url: jdbc:postgresql://${INVENTORY_DB_HOST:localhost}:${INVENTORY_DB_PORT:5432}/${INVENTORY_DB_NAME:orderflow_inventory}
    username: ${INVENTORY_DB_USERNAME:orderflow}
    password: ${INVENTORY_DB_PASSWORD:change-me}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connect-timeout: 2s
      timeout: 2s

server:
  port: ${INVENTORY_SERVICE_PORT:8082}

security:
  internal:
    token: ${INTERNAL_SERVICE_TOKEN:local-internal-service-token}

orderflow:
  cache:
    products:
      ttl: ${PRODUCT_CACHE_TTL:PT10M}

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics

  endpoint:
    health:
      show-details: never

  metrics:
    tags:
      application: ${spring.application.name}