spring:
  application:
    name: inventory-service
  profiles:
    default: local

server:
  port: ${SERVER_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: inventory-service
    version: 0.0.1-SNAPSHOT
