server:
  forward-headers-strategy: framework

  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: never

      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework.security: WARN